### ISSUE TITLE
Memory leak in xmlSecParseMemory()

### ISSUE THREAD

**Issue by bshastry** [lsh123/xmlsec#199]
Hi,

There is a memory leak in the said API that is likely caused because of not freeing an xml document in a parsing context in *addition* to freeing the context itself (which is currently done in parser.c)

Here's the report, the xml file contains a single new line only (`\x0a`)
```
==1==ERROR: LeakSanitizer: detected memory leaks                                                                               [53/1911]

Direct leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x504807 in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:121
    #1 0x68b41b in xmlNewDoc /src/libxml2/tree.c:1171:23
    #2 0x819686 in xmlSAX2StartDocument /src/libxml2/SAX2.c:1013:22
    #3 0x66635a in xmlParseDocument /src/libxml2/parser.c:10654:9
    #4 0x54a79e in xmlSecParseMemory /src/xmlsec/src/parser.c:536:11
    #5 0x547500 in LLVMFuzzerTestOneInput /src/xmlsec_target.c:12:21
    #6 0x5ae8ac in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:526:13
    #7 0x5ace9f in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoo
p.cpp:451:3
    #8 0x5b02ff in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:657:19
    #9 0x5b3236 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<c
har> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/
libfuzzer/FuzzerLoop.cpp:788:5
    #10 0x591bae in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:758:6
    #11 0x5850ec in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #12 0x7f2f1910982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x504807 in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:121
    #1 0x68b41b in xmlNewDoc /src/libxml2/tree.c:1171:23
    #2 0x819686 in xmlSAX2StartDocument /src/libxml2/SAX2.c:1013:22
    #3 0x66635a in xmlParseDocument /src/libxml2/parser.c:10654:9
    #4 0x54a79e in xmlSecParseMemory /src/xmlsec/src/parser.c:536:11
    #5 0x547500 in LLVMFuzzerTestOneInput /src/xmlsec_target.c:12:21
    #6 0x5ae8ac in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:526:13
    #7 0x5ace9f in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoo
p.cpp:451:3
    #8 0x5b18f9 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, 
std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char
> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:715:5
    #9 0x5b2ba8 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<c
har> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/
libfuzzer/FuzzerLoop.cpp:755:3
    #10 0x591bae in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:75
8:6
    #11 0x5850ec in main /src/libfuzzer/FuzzerMain.cpp:20:10
```

**Comment by lsh123** [comment]
xmlSecParseMemory() returns the parsed xmlDoc. Can you share the program that calls xmlSecParseMemory()?

**Comment by bshastry** [comment]
Hi,

This is the program I am fuzzing atm

```
#include <xmlsec/buffer.h>
#include <xmlsec/parser.h>

void ignore (void* ctx, const char* msg, ...) {
          // Error handler to avoid spam of error messages from libxml parser.
}

int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    xmlSetGenericErrorFunc(NULL, &ignore);
    xmlSecBufferPtr buf = xmlSecBufferCreate(size);
    xmlSecBufferSetData(buf, data, size);
    xmlDocPtr doc = xmlSecParseMemory(xmlSecBufferGetData(buf),
                    xmlSecBufferGetSize(buf), 0);

    if (doc != NULL) xmlFreeDoc(doc);
    xmlSecBufferDestroy(buf);
    return 0;
}
```

**Comment by bshastry** [comment]
Hello,

Would you be interesting in enrolling xmlsec at oss-fuzz for continual fuzzing? I have a pull request waiting to happen :smile:

**Comment by lsh123** [comment]
I love PRs :)

**Comment by bshastry** [comment]
Great. You have one more #204 :smile:
